#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 23 18:48:11 JST 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim div64_l8_u5_gznk_test_behav -key {Behavioral:sim_1:Functional:div64_l8_u5_gznk_test} -tclbatch div64_l8_u5_gznk_test.tcl -log simulate.log"
xsim div64_l8_u5_gznk_test_behav -key {Behavioral:sim_1:Functional:div64_l8_u5_gznk_test} -tclbatch div64_l8_u5_gznk_test.tcl -log simulate.log

